### ISSUE TITLE
Untranslatable app

### ISSUE THREAD

**Issue by Anne017** [WammKD/Emergency-Chat#1]
Hello !
Very interesting app, I would like to contribute and translate it in French.
However, the .pot files (because there are two of them) are not up-to-date.
The i18n.tr() structure seems to be in all the QML files though.
Could you please regenerate a .pot file?
Thanks for your work.

**Comment by WammKD** [comment]
Hi, @Anne017!

I believe I updated things correctly (and added some other areas that probably ought to have translations); lemme know if I've updated the correct file?

And thank you for the translation!

**Comment by Anne017** [comment]
Perfect!
You will find a French translation in #2
